# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dlock-be/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: root
